import Navbar from '@/components/navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/footer';
import ThemeProvide from '@/context/ThemeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next-App-router学习',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} `}>
        <ThemeProvide>
          <div className='container px-16 py-0 min-h-screen flex flex-col justify-between'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvide>
      </body>
    </html>
  );
}
